

CREATE TABLE tab_login (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL ,
    COGNOME VARCHAR (50) NOT NULL,
    PAESE VARCHAR(50) NOT NULL,
    MAIL VARCHAR(50) NOT NULL,
    SESSO VARCHAR(30) NOT NULL,
    PW VARCHAR(50) NOT NULL,
    CONF_PW VARCHAR(50) NOT NULL
) 