version: '3.8'

services:
  db:
    container_name: db_principale
    build: 
          context: ./database_principale
          dockerfile: Dockerfile
    ports:
      - "5432:5432"
    restart: always
    networks:
      mynetwork:

  db_log:
    container_name: db_login
    build: 
          context: ./database_login
          dockerfile: Dockerfile
    ports:
      - "5433:5433"
    restart: always
    networks:
      mynetwork:

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 'carta.ema24@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: '1234'
    networks:
      mynetwork:

  data:
    container_name: data_obtainment
    build: 
          context: ./data_obtainment
          dockerfile: Dockerfile
    ports:
      - "5006:80"
    depends_on:
      - db
    networks:
      mynetwork:

networks:
  mynetwork: