
-- CREATE DATABASE PARTITE_database;

CREATE TABLE PARTITE
(
  DATA_PARTITA CHAR(50),
  SQUADRA CHAR(50),
  ORA  CHAR(50),
  COMPETIZIONE CHAR(50),
  GIRONE CHAR(50),
  GIORNO  CHAR(50),
  STADIO CHAR(50),
  RISULTATO CHAR(50),
  RF INT,
  RS INT,
  AVVERSARIO CHAR(50),
  xG FLOAT,
  xGA FLOAT,
  POSSESSO INT,
  SPETTATORI INT,
  CAPITANO CHAR(50),
  FORMAZIONE CHAR(50),
  ARBITRO CHAR(50),
  REPORT_PARTITA CHAR(50),
  
  PRIMARY KEY (DATA_PARTITA, SQUADRA)
);


