apiVersion: apps/v1
kind: Deployment
metadata:
  name: cucina-page-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cucina-page
  template:
    metadata:
      labels:
        app: cucina-page
    spec:
      containers:
      - name: cucina-page
        image: ecarta/cucina-page:latest
        ports:
        - containerPort: 8070

---
apiVersion: v1
kind: Service
metadata:
  name: cucina-page-service # Sets service name
  labels:
    app: cucina-page # Labels and Selectors
spec:
  type: LoadBalancer # Sets service type
  selector:
    app: cucina-page
  ports:
    - name: cucina-page-port
      port: 8070 # Sets port to run the postgres application
      targetPort: 80