version: '3.8'

services:
  db:
    container_name: db_ordini
    build: 
          context: ./database
          dockerfile: Dockerfile
    ports:
      - "5432:5432"
    restart: always


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 'carta.ema24@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: '1234'

    
  ordini_page:
    container_name: ordini_page
    build:
          context: ./ordini_page
          dockerfile: Dockerfile
    ports:
      - "5006:80"
  
  access_page:
    container_name: access_page
    build:
          context: ./access_page
          dockerfile: Dockerfile
    ports:
      - "8091:80"
 
 