apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordini-page-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordini-page
  template:
    metadata:
      labels:
        app: ordini-page
    spec:
      containers:
      - name: ordini-page
        image: ecarta/ordini-page:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: ordini-page-service # Sets service name
  labels:
    app: ordini-page # Labels and Selectors
spec:
  type: LoadBalancer # Sets service type
  selector:
    app: ordini-page
  ports:
    - name: ordini-page-port
      port: 8080 # Sets port to run the postgres application
      targetPort: 80